---
title: "Tidyverse"
author: "Sagar Wadke"
---

# Challenge 1

```{r}
# 1.0 Load libraries ----
suppressWarnings({
  library(tidyverse)
  library(readxl)
  library(lubridate)
})

bike_orderlines_wrangled_tbl <- read_excel(path = "C:\\Users\\Sagar\\Documents\\GitHub\\ss23-bdsb-SagarWadke\\bike_data\\bike_orderlines.xlsx")

#challenge_tidyverse_1
new_tbl <- bike_orderlines_wrangled_tbl %>%
  
  #Select Columns
  select(location, total_price) %>%
  
  #Separate city and state
  separate(location, into = c("city", "state"), sep = ", ",remove = TRUE)  %>%
  
  #Group states and sales
  group_by(state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

new_tbl %>%
  
  # Setup canvas with the columns year (x-axis) and sales (y-axis)
  ggplot(aes(x = state, y = sales)) +
  
  # Geometries
  geom_col(fill = "#2DC6D6") + # Use geom_col for a bar plot
  geom_label(aes(label = sales_text)) + # Adding labels to the bars
  geom_smooth(method = "lm", se = FALSE) + # Adding a trendline
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  # Formatting
  # scale_y_continuous(labels = scales::dollar) + # Change the y-axis. 
  # Again, we have to adjust it for euro values
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title    = "Revenue by state",
    subtitle = "",
    x = "State",
    y = "Revenue"
  )

```
### Which state has the highest revenue?

It can be noted from the graph that **"North Rhine-Westphalia"** has the highest revenue.

# Challenge 2

## Analyze the sales by location and year. 

```{r}
#challenge_tidyverse_2
new_tbl2 <- bike_orderlines_wrangled_tbl %>%
  
  # Select columns and add a year
  select(order_date, location, total_price) %>%
  separate(location, into = c("city", "state"), sep = ", ",remove = TRUE)  %>%
  mutate(year = year(order_date)) %>%
  
  # Group by and summarize year and main category
  group_by(year, state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  # Format $ Text
  mutate(sales_text = scales::dollar(sales, big.mark = ".", 
                                     decimal.mark = ",", 
                                     prefix = "", 
                                     suffix = " €"))

new_tbl2 %>%
  
  # Set up x, y, fill
  ggplot(aes(x = year, y = sales, fill = state)) +
  
  # Geometries
  geom_col() + # Run up to here to get a stacked bar plot
  geom_smooth(method = "lm", se = FALSE) + #trendline
  # Facet
  facet_wrap(~ state) +
  
  # Formatting
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", 
                                                    decimal.mark = ",", 
                                                    prefix = "", 
                                                    suffix = " €")) +
  labs(
    title = "Revenue by year and state",
    subtitle = "",
    fill = "State" # Changes the legend name
  )
  
```